apiVersion: v1
kind: Service

metadata:
  name: uptime-kuma-service
  labels:
    app: uptime-kuma

spec:
  type: ClusterIP
  selector:
    app: uptime-kuma

  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      name: http