apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: immich-db-pvc
  labels:
    app: immich

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: immich-model-cache-pvc
  labels:
    app: immich

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi