apiVersion: v1
kind: Service

metadata:
  name: nginx-proxy-service
  labels:
    app: nginx-proxy

spec:
  type: ClusterIP
  selector:
    app: nginx-proxy

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
