server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://homepage-service.platform.svc.cluster.local:3000;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location = /homebasket { return 301 $scheme://$http_host/homebasket/; }
    location /homebasket/ {
        proxy_pass http://home-basket-service.platform.svc.cluster.local:80/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location = /homeassistant { return 301 http://$host:8123/; }
    location /homeassistant/  { return 301 http://$host:8123/; }

    location = /immich { return 301 http://$host:2283/; }
    location /immich/  { return 301 http://$host:2283/; }

    location = /jellyfin { return 301 http://$host:8096/; }
    location /jellyfin/  { return 301 http://$host:8096/; }

    location = /kuma { return 301 http://$host:3001/; }
    location /kuma/  { return 301 http://$host:3001/; }

    location = /nextexplorer { return 301 http://$host:3081/; }
    location /nextexplorer/  { return 301 http://$host:3081/; }

    location = /health { return 301 $scheme://$http_host/health/; }
    location /health {
        proxy_pass http://whoami-service.platform.svc.cluster.local:80;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://homepage-service.platform.svc.cluster.local:3000;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location = /homeassistant { return 301 http://$host:8123/; }
    location /homeassistant/  { return 301 http://$host:8123/; }

    location = /immich { return 301 http://$host:2283/; }
    location /immich/  { return 301 http://$host:2283/; }

    location = /jellyfin { return 301 http://$host:8096/; }
    location /jellyfin/  { return 301 http://$host:8096/; }

    location = /kuma { return 301 http://$host:3001/; }
    location /kuma/  { return 301 http://$host:3001/; }

    location = /nextexplorer { return 301 http://$host:3081/; }
    location /nextexplorer/  { return 301 http://$host:3081/; }

    location = /health { return 301 $scheme://$http_host/health/; }
    location /health {
        proxy_pass http://whoami-service.platform.svc.cluster.local:80;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}