apiVersion: apps/v1
kind: Deployment

metadata:
  name: home-basket
  labels:
    app: home-basket

spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-basket

  template:
    metadata:
      labels:
        app: home-basket
    spec:
      imagePullSecrets:
        - name: ghcr-login
      containers:
        - name: home-basket
          image: ghcr.io/llabhishekll/home-basket:latest # {"$imagepolicy": "flux-system:home-basket-policy"}

          ports:
            - containerPort: 80

          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
