apiVersion: v1
kind: Service

metadata:
  name: next-explorer-service
  labels:
    app: next-explorer

spec:
  type: ClusterIP
  selector:
    app: next-explorer

  ports:
    - protocol: TCP
      port: 3081
      targetPort: 3000
      name: http