apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: next-explorer-config-pvc
  labels:
    app: next-explorer

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi